---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	input_url(input_url)
	extract_content(extract_content)
	check_cache(check_cache)
	classify(classify)
	synthesize(synthesize)
	verify(verify)
	judge(judge)
	improve(improve)
	save_summary(save_summary)
	augment(augment)
	quiz(quiz)
	quiz_judge(quiz_judge)
	quiz_improve(quiz_improve)
	persona(persona)
	persona_safety_check(persona_safety_check)
	save_cache(save_cache)
	schedule(schedule)
	__end__([<p>__end__</p>]):::last
	__start__ --> input_url;
	augment --> quiz;
	check_cache -. &nbsp;not_cached&nbsp; .-> classify;
	check_cache -. &nbsp;cached&nbsp; .-> schedule;
	classify --> synthesize;
	extract_content -. &nbsp;INVALID&nbsp; .-> __end__;
	extract_content -. &nbsp;SAFE&nbsp; .-> check_cache;
	improve --> verify;
	input_url -. &nbsp;invalid&nbsp; .-> __end__;
	input_url -. &nbsp;valid&nbsp; .-> extract_content;
	judge -.-> improve;
	judge -.-> save_summary;
	persona --> persona_safety_check;
	persona_safety_check --> save_cache;
	quiz --> quiz_judge;
	quiz_improve --> quiz_judge;
	quiz_judge -.-> persona;
	quiz_judge -. &nbsp;improve&nbsp; .-> quiz_improve;
	save_cache --> schedule;
	save_summary -.-> augment;
	save_summary -.-> quiz;
	synthesize --> verify;
	verify --> judge;
	schedule --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
